apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/traefik
  - ../base/cert-manager
  - ../base/external-secrets
  - ../base/metallb
  - ../base/external-dns
  - ../base/openebs
patches:
  - target:
      kind: HelmRelease
      name: traefik
      namespace: traefik
    patch: |
      - op: replace
        path: /spec/values/ingressRoute/dashboard/matchRule
        value: Host(`traefik.ducknet.io`)
