apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-ducknet-tls
spec:
  secretName: traefik-ducknet-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - ducknet.io
    - "*.ducknet.io"
