apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns-credentials
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflare-dns-credentials
    creationPolicy: Owner
  data:
    - secretKey: CLOUDFLARE_DNS_API_TOKEN
      remoteRef:
        key: cloudflare-dns-api-token
        property: token
    - secretKey: CLOUDFLARE_EMAIL
      remoteRef:
        key: cloudflare-dns-api-token
        property: email
