apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
  - ../base/external-secrets-demo
patches:
  - target:
      kind: HTTPRoute
      name: podinfo
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: podinfo.orb.local
