---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs-validation
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: openebs-config
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/homelab/openebs-validation
  prune: true
  wait: true
  timeout: 5m0s
