apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-unifi-api-key
  namespace: external-dns
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: external-dns-unifi-api-key
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: external-dns-unifi-api-key/api-key
